name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#workflow fispatch
#workflow-dispatch

  schedule:
  - cron: "0 2 * * 1-5"
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: g++ file.cpp
    
