name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#workflow fispatch
#workflow-dispatch

  schedule:
  - cron: "0 2 * * 1-5"
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: g++ file.cpp
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck

  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: g++ file.cpp
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck

    
